apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pnlnz18rd-python-gitops
  description: This is GitOps manifest for pnlnz18rd-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: pnlnz18rd-python
    backstage.io/kubernetes-id: pnlnz18rd-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: pnlnz18rd-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:pnlnz18rd-python
